check result code before using jq

diff --git a/tekton/tasks/task-va.yaml b/tekton/tasks/task-va.yaml
--- a/tekton/tasks/task-va.yaml
+++ b/tekton/tasks/task-va.yaml
@@ -118,10 +118,15 @@ spec:
 
         for iteration in {1..30}
         do
-          BX_CR_VA=$(ibmcloud cr va $PIPELINE_IMAGE_URL --output json | jq -r '.[] .status')
-          echo "BX_CR_VA=${BX_CR_VA}"
-          if [[ "${BX_CR_VA}" == "OK" ]]; then
-            break
+          BX_CR_VA=$(ibmcloud cr va $PIPELINE_IMAGE_URL --output json)
+          if [[ $? -eq 0 ]]; then
+            BX_CR_VA=$(echo ${BX_CR_VA} | jq -r '.[] .status')
+            echo "BX_CR_VA=${BX_CR_VA}"
+            if [[ "${BX_CR_VA}" == "OK" ]]; then
+              break
+            fi
+          else
+            echo "error while running va check: ${BX_CR_VA}"
           fi
 
           echo -e "A vulnerability report was not found for the specified image, either the image doesn't exist or the scan hasn't completed yet. Waiting for scan to complete.."
