add automatic retries to cluster config

diff --git a/tekton/listeners/pgbouncer/task-deploy-pgbouncer.yaml b/tekton/listeners/pgbouncer/task-deploy-pgbouncer.yaml
--- a/tekton/listeners/pgbouncer/task-deploy-pgbouncer.yaml
+++ b/tekton/listeners/pgbouncer/task-deploy-pgbouncer.yaml
@@ -96,7 +96,22 @@ spec:
         set +x
         ibmcloud login -a ${API} -r ${REGION} --apikey ${API_KEY}
         set -x
-        ibmcloud ks cluster config  --cluster ${CLUSTER_NAME}
+        function cluster_config() {
+            # 1 - cluster name
+            for iteration in {1..30}
+            do
+                echo "Running cluster config for cluster $1: $iteration / 30"
+                ibmcloud ks cluster config --cluster $1
+                if [[ $? -eq 0 ]]; then
+                    return 0
+                else
+                    echo "Cluster config for $1 failed. Trying again..."
+                    sleep 5
+                fi
+            done
+            return 1
+        }
+        cluster_config ${CLUSTER_NAME}
         set -e
 
         chmod a+x ${SCRIPT_DIRECTORY}/scripts/deploy_pgbouncer_tekton.sh
diff --git a/tekton/restart/task-restart-depoyment.yaml b/tekton/restart/task-restart-depoyment.yaml
--- a/tekton/restart/task-restart-depoyment.yaml
+++ b/tekton/restart/task-restart-depoyment.yaml
@@ -69,7 +69,22 @@ spec:
         ibmcloud plugin install -f kubernetes-service
         ibmcloud login -a ${API} -r ${ENVIRONMENT} --apikey ${API_KEY}
 
-        ibmcloud ks cluster config --cluster ${CLUSTER_NAME}
+        function cluster_config() {
+            # 1 - cluster name
+            for iteration in {1..30}
+            do
+                echo "Running cluster config for cluster $1: $iteration / 30"
+                ibmcloud ks cluster config --cluster $1
+                if [[ $? -eq 0 ]]; then
+                    return 0
+                else
+                    echo "Cluster config for $1 failed. Trying again..."
+                    sleep 5
+                fi
+            done
+            return 1
+        }
+        cluster_config ${CLUSTER_NAME}
 
         RS=$( kubectl -n${CLUSTER_NAMESPACE} get pods | grep ${SERVICE_NAME}  | rev | cut -f2- -d- | rev | sort -u | head -1 )
         kubectl -n${CLUSTER_NAMESPACE} rollout restart deployment ${SERVICE_NAME}
diff --git a/tekton/tasks/task-deploy.yaml b/tekton/tasks/task-deploy.yaml
--- a/tekton/tasks/task-deploy.yaml
+++ b/tekton/tasks/task-deploy.yaml
@@ -122,7 +122,22 @@ spec:
         ls -F
         ls -F cd-pipeline-kubernetes
 
-        ibmcloud ks cluster config --cluster ${CLUSTER_NAME}
+        function cluster_config() {
+            # 1 - cluster name
+            for iteration in {1..30}
+            do
+                echo "Running cluster config for cluster $1: $iteration / 30"
+                ibmcloud ks cluster config --cluster $1
+                if [[ $? -eq 0 ]]; then
+                    return 0
+                else
+                    echo "Cluster config for $1 failed. Trying again..."
+                    sleep 5
+                fi
+            done
+            return 1
+        }
+        cluster_config ${CLUSTER_NAME}
 
         INGRESS_SUBDOMAIN=$(ibmcloud ks cluster get -s --cluster ${CLUSTER_NAME} | grep -i "Ingress subdomain:" | awk '{print $3;}')
         echo "INGRESS SUB DOMAIN: $INGRESS_SUBDOMAIN"
diff --git a/tekton/tasks/task-dind.yaml b/tekton/tasks/task-dind.yaml
--- a/tekton/tasks/task-dind.yaml
+++ b/tekton/tasks/task-dind.yaml
@@ -103,7 +103,22 @@ spec:
         IMAGE_URL=${IMAGE_NAME}:${IMAGE_TAG}
         DOCKERFILE=${DOCKERFILE}
 
-        ibmcloud ks cluster config --cluster ${BUILD_CLUSTER}
+        function cluster_config() {
+            # 1 - cluster name
+            for iteration in {1..30}
+            do
+                echo "Running cluster config for cluster $1: $iteration / 30"
+                ibmcloud ks cluster config --cluster $1
+                if [[ $? -eq 0 ]]; then
+                    return 0
+                else
+                    echo "Cluster config for $1 failed. Trying again..."
+                    sleep 5
+                fi
+            done
+            return 1
+        }
+        cluster_config ${CLUSTER_NAME}
 
         kubectl --namespace otc-dev get pods 
         kubectl --namespace otc-dev port-forward $(kubectl --namespace otc-dev get pods | grep docker | awk '{print $1;}') 2375:2375 > /dev/null 2>&1 &
diff --git a/tekton/tasks/task-publish.yaml b/tekton/tasks/task-publish.yaml
--- a/tekton/tasks/task-publish.yaml
+++ b/tekton/tasks/task-publish.yaml
@@ -139,7 +139,22 @@ spec:
 
         ibmcloud login -a ${API} -r ${REGISTRY_REGION} --apikey ${DRY_RUN_API_KEY}
 
-        ibmcloud ks cluster config --cluster ${DRY_RUN_CLUSTER}
+        function cluster_config() {
+            # 1 - cluster name
+            for iteration in {1..30}
+            do
+                echo "Running cluster config for cluster $1: $iteration / 30"
+                ibmcloud ks cluster config --cluster $1
+                if [[ $? -eq 0 ]]; then
+                    return 0
+                else
+                    echo "Cluster config for $1 failed. Trying again..."
+                    sleep 5
+                fi
+            done
+            return 1
+        }
+        cluster_config ${DRY_RUN_CLUSTER}
 
         if [ -z "${MAJOR_VERSION}" ] ||  [ -z "${MINOR_VERSION}" ] ||  [ -z "${CHART_REPO}" ]; then
           echo "Major & minor version and chart repo vars need to be set"
diff --git a/tekton/tasks/task-run-hc.yaml b/tekton/tasks/task-run-hc.yaml
--- a/tekton/tasks/task-run-hc.yaml
+++ b/tekton/tasks/task-run-hc.yaml
@@ -61,7 +61,22 @@ spec:
         echo Logging into Deployment account
         ibmcloud login --apikey ${API_KEY} -r ${REGION} 
 
-        ibmcloud ks cluster config  --cluster ${CLUSTER_NAME} --skip-rbac
+        function cluster_config() {
+            # 1 - cluster name
+            for iteration in {1..30}
+            do
+                echo "Running cluster config for cluster $1: $iteration / 30"
+                ibmcloud ks cluster config --cluster $1
+                if [[ $? -eq 0 ]]; then
+                    return 0
+                else
+                    echo "Cluster config for $1 failed. Trying again..."
+                    sleep 5
+                fi
+            done
+            return 1
+        }
+        cluster_config ${CLUSTER_NAME}
 
         chmod a+x ${SCRIPT_DIRECTORY}/scripts/healthcheck.sh 
         ${SCRIPT_DIRECTORY}/scripts/healthcheck.sh ${CLUSTER_NAMESPACE} ${SOURCE_DIRECTORY}/cr/components.txt
