Converted to use grant's generic pipeline

diff --git a/tekton/secret-update/task-bss-credential-rotate.yaml b/tekton/secret-update/task-bss-credential-rotate.yaml
--- a/tekton/secret-update/task-bss-credential-rotate.yaml
+++ b/tekton/secret-update/task-bss-credential-rotate.yaml
@@ -33,16 +33,6 @@ spec:
           valueFrom:
             fieldRef:
               fieldPath: metadata.annotations['devops.cloud.ibm.com/triggered-by']
-        - name: REDIS_CERT_BASE64
-          valueFrom:
-            secretKeyRef:
-              name: cd-secret
-              key: REDIS_CERT
-        - name: REDIS_URL
-          valueFrom:
-            secretKeyRef:
-              name: cd-secret
-              key: REDIS_URL
         - name: WEBHOOK_SECRET_UPDATER
           valueFrom:
             secretKeyRef:
@@ -53,14 +43,19 @@ spec:
             secretKeyRef:
               name: cd-secret
               key: WEBHOOK_TOKEN_SECRET_UPDATER
+        - name: BSS_JSON
+          valueFrom:
+            secretKeyRef:
+              name: cd-secret
+              key: BSS_JSON
       command: ["/bin/bash", "-c"]
       args:
         - |
           set -e -o pipefail
           cd /workspace
-
+          echo ${BSS_JSON}
           testResults=`sed 's/$/\\\\n/' test-results.txt | tr -d '\n'`
-          SECRETS="ICD_REDIS_CERT_BASE64=${REDIS_CERT_BASE64},REDIS_URLS=${REDIS_URL}"
+          SECRETS="BSS_CLIENT_SECRET=${SECRET},com_ibm_team_integration_pipeline_bss_password=${SECRET}"
           cat << EOF > data.json
           {
               "secrets": "$SECRETS",
@@ -68,7 +63,7 @@ spec:
               "cr-backout-plan": "$(params.cr-backout-plan)",
               "cr-description": "$(params.cr-description)",
               "cr-purpose": "$(params.cr-purpose)",
-              "cr-skip": "$(params.cr-skip)",
+              "cr-skip": "true",
               "ctask-description": "$(params.ctask-description)",
               "ctask-short-description": "$(params.ctask-short-description)",
               "ctask-test-results": "$testResults",
@@ -87,14 +82,14 @@ spec:
           }
           EOF
           cat data.json
-          echo "Invoking the secret updater webhook..."
-          if curl -X POST "$WEBHOOK_SECRET_UPDATER" \
-              -H "X-Token: $WEBHOOK_TOKEN_SECRET_UPDATER" \
-              -H "Content-Type: application/json" \
-              -d "@data.json" \
-              --fail --silent --show-error | grep pending; then
-              echo "Successfully invoked the webhook."
-          else
-              echo "Failed to invoke the webhook."
-              exit 1;
-          fi
+          #echo "Invoking the secret updater webhook..."
+          #if curl -X POST "$WEBHOOK_SECRET_UPDATER" \
+          #    -H "X-Token: $WEBHOOK_TOKEN_SECRET_UPDATER" \
+          #    -H "Content-Type: application/json" \
+          #    -d "@data.json" \
+          #    --fail --silent --show-error | grep pending; then
+          #    echo "Successfully invoked the webhook."
+          #else
+          #    echo "Failed to invoke the webhook."
+          #    exit 1;
+          #fi
