removed comments to enable bss secret rotation call

diff --git a/tekton/secret-update/task-bss-credential-rotate.yaml b/tekton/secret-update/task-bss-credential-rotate.yaml
--- a/tekton/secret-update/task-bss-credential-rotate.yaml
+++ b/tekton/secret-update/task-bss-credential-rotate.yaml
@@ -88,14 +88,14 @@ spec:
           }
           EOF
           cat data.json
-          #echo "Invoking the secret updater webhook..."
-          #if curl -X POST "$WEBHOOK_SECRET_UPDATER" \
-          #    -H "X-Token: $WEBHOOK_TOKEN_SECRET_UPDATER" \
-          #    -H "Content-Type: application/json" \
-          #    -d "@data.json" \
-          #    --fail --silent --show-error | grep pending; then
-          #    echo "Successfully invoked the webhook."
-          #else
-          #    echo "Failed to invoke the webhook."
-          #    exit 1;
-          #fi
+          echo "Invoking the secret updater webhook..."
+          if curl -X POST "$WEBHOOK_SECRET_UPDATER" \
+              -H "X-Token: $WEBHOOK_TOKEN_SECRET_UPDATER" \
+              -H "Content-Type: application/json" \
+              -d "@data.json" \
+              --fail --silent --show-error | grep pending; then
+              echo "Successfully invoked the webhook."
+          else
+              echo "Failed to invoke the webhook."
+              exit 1;
+          fi
