Fix VA scan ... again

diff --git a/tekton/agent/buildAgentTask.yaml b/tekton/agent/buildAgentTask.yaml
--- a/tekton/agent/buildAgentTask.yaml
+++ b/tekton/agent/buildAgentTask.yaml
@@ -221,8 +221,36 @@ spec:
         APPLICATION_VERSION=$(cat /artifacts/appVersion)
         export HOME=/root && [ -f /root/.nvm/nvm.sh ] && chmod +x /root/.nvm/nvm.sh && source /root/.nvm/nvm.sh
         cd /work
-        chmod u+x /work/scripts/pipeline_va_tek.sh
-        "$_"
+        
+        IBM_CLOUD_API=${IBM_CLOUD_API:-cloud.ibm.com}
+        
+        ibmcloud login -a ${IBM_CLOUD_API} -r ${ACCOUNT_REGION} --apikey ${DOCKER_PASSWORD}
+        ibmcloud cr region-set global
+        # default value for PIPELINE_IMAGE_URL -- uncomment and customize as needed
+        export PIPELINE_IMAGE_URL="${IMAGE_URL}:${APPLICATION_VERSION}"
+        echo "PIPELINE_IMAGE_URL=${PIPELINE_IMAGE_URL}"
+
+        for iteration in {1..30}
+        do
+          BX_CR_VA=$(ibmcloud cr va $PIPELINE_IMAGE_URL --output json)
+          if [[ $? -eq 0 ]]; then
+            BX_CR_VA=$(echo -n ${BX_CR_VA} | jq -r '.[] .status')
+            echo "BX_CR_VA=${BX_CR_VA}"
+            if [[ "${BX_CR_VA}" == "OK" ]]; then
+              break
+            fi
+          else
+            echo "error while running va check: ${BX_CR_VA}"
+          fi
+          echo -e "A vulnerability report was not found for the specified image, either the image doesn't exist or the scan hasn't completed yet. Waiting for scan to complete.."
+          sleep 10
+        done
+        echo "${BX_CR_VA}"
+        if [[ ! "${BX_CR_VA}" == "OK" ]]; then
+          echo "ERROR: The vulnerability scan was not successful, check the output of the command and try again."
+          exit 1
+        fi
+
   sidecars:
     - image: docker:dind
       name: server
